ministryofjustice/hmpps-accredited-programmes-manage-and-deliver-api

Dockerfile
Seeing the following error on API startup:
`SQL State  : 08006
Error Code : 0
Message    : Could not open SSL root certificate file /home/appuser/.postgresql/root.crt.`
- Add AWS RDS root cert to Java truststore in Dockerfile
=> [APG-963] Add AWS RDS root cert to Java truststore in Dockerfile

build.gradle.kts, docker-compose.yml, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/entity/MessageHistoryEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/entity/ReferralEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/entity/ReferralStatusHistoryEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/listener/ReferralCreatedHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/listener/model/DomainEventsMessage.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/repository/ReferralRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/repository/ReferralStatusHistoryRepository.kt, src/main/resources/db/migration/V2__create_referral_tables.sql, src/main/resources/db/migration/V3__add_referral_to_message_history.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/entity/MessageHistoryEntityTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/entity/ReferralEntityTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/factory/EntityFactoriesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/factory/MessageHistoryEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/factory/ReferralEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/factory/ReferralStatusHistoryEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/integration/IntegrationTestBase.kt
- Created `ReferralEntity` and `ReferralStatusHistoryEntity` with mappings
- Added corresponding repositories and factories for testing
- Extended `MessageHistoryEntity` to include optional referral association
- Updated tests and integration tests for referral handling
- Added database migrations for referral-related tables
- Updated Docker Compose to include PostgreSQL and LocalStack configurations for testing
=> [APG-1012] Add support for referral entity, referral status history, and related persistence logic

build.gradle.kts, docker-compose.yml, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/ApiExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/controller/CaseListController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/model/ReferralCaseListItem.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/config/EnumMappingConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/entity/ReferralCaseListItemViewEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/repository/ReferralCaseListItemRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/ReferralCaseListItemService.kt, src/main/resources/db/migration/V8__add_referral_id_column_to_caselist_item_view.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/controller/CaseListControllerIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/common/RestResponsePage.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/common/TestDataGenerator.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/factory/ReferralEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/integration/GetCaseListItemsTest.kt, src/test/resources/db/testData/setup.sql, src/test/resources/db/testData/teardown.sql
This PR implements Pagination in the GetCaseList controller. This PR also now returns the data from the `caseListItemView` rather than the hardcoded data that was there previously. Example API response:
```json
{
"content": [
{
"referralId": "a8a83c3e-d779-47d5-849f-bb2635666344",
"crn": "CRN-66666",
"personName": "James Hayden",
"referralStatus": "STARTED"
},
{
"referralId": "54b1a0ac-ab67-4dde-871f-b59b675cbc8c",
"crn": "CRN-777777",
"personName": "Pete Grims",
"referralStatus": "CREATED"
},
{
"referralId": "81229aaa-bb3a-4705-8015-99052bafab58",
"crn": "CRN-999999",
"personName": "Alex River",
"referralStatus": "CREATED"
},
{
"referralId": "39fde7e8-d2e3-472b-8364-5848bf673aa6",
"crn": "CRN-888888",
"personName": "Jane Adams",
"referralStatus": "CREATED"
},
{
"referralId": …
```
=> APG-1056: Return a paged list of referrals

src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/controller/PniController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/model/DomainScores.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/model/IndividualNeedsScores.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/model/PniScore.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/client/oasysApi/model/PniCalculation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/client/oasysApi/model/PniResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/PniService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/controller/PniControllerIntegrationTest.kt
* Introduced a new endpoint for accessing PNI scores by CRN, including domain score mapping and integration with the respective service.
* Added integration tests for success and failure scenarios
The endpoint was developed to provide the required data for the the Programme needs Identifier section of the View referrals screen:
=> Add PNI score endpoint with domain score mapping

src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/client/nDeliusIntegrationApi/model/NDeliusPersonalDetails.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/controller/ReferralControllerIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/common/DataGenerators.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/factory/NDeliusPersonalDetailsFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/ServiceUserServiceTest.kt, wiremock_mappings/nDeliusMock.json
Currently the nDelius personal details response expects middleName to be not null.
This PR fixes this as middle names can be null
=> Allow middle name to be null for nDelius Personal details response

.run/Local - Run.run.xml, README.md, docker-compose.yml, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/model/PersonalDetails.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/client/findAndReferInterventionApi/model/FindAndReferReferralDetails.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/entity/ReferralEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/entity/type/InterventionType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/entity/type/PersonReferenceType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/entity/type/SettingType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/entity/type/SourcedFromReferenceType.kt, src/main/resources/application-local.yml, src/main/resources/application.yml, src/main/resources/db/local/V99_1__add_local_referral_data.sql, src/main/resources/db/migration/V10__Add_event_number_column_to_referral_table.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/model/ReferralTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/client/findAndReferInterventionApi/FindAndReferInterventionApiClientIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/common/DataGenerators.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/factory/EntityFactoriesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/factory/FindAndReferReferralDetailsFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/factory/ReferralEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/listener/DomainEventsListenerIntegrationTest.kt, src/test/resources/events/interventions/communityReferralCreatedEvent.json
This PR updates the Find and Refer referral details model to accept the `sourcedFromReference` field we need to store in Manage and Deliver.
It also enables connection to the dev instances of Find and Refer and NDelius for local development so we do not have to mock these services any more.
=> Update find and refer details model to accept sourcedFromReference

src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/controller/ReferralController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/model/Offence.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/model/OffenceHistory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/client/nDeliusIntegrationApi/NDeliusIntegrationApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/client/nDeliusIntegrationApi/model/Offence.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/client/nDeliusIntegrationApi/model/Offences.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/entity/ReferralEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/OffenceService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/controller/ReferralControllerIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/client/nDeliusIntegrationApi/NDeliusIntegrationApiClientIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/factory/EntityFactoriesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/factory/OffenceFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/factory/OffencesFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/integration/wiremock/stubs/NDeliusApiStubs.kt
- Integrated with NDelius API to fetch offence data.
- Introduced new `Offence` and `OffenceHistory` models.
- Extended `ReferralController` with endpoint for offence history retrieval.
- Added supporting service, factories, and tests for offence-related functionality.
=> [APG-1110] Add offence history retrieval via NDelius API integration and expose API endpoint in Referral controller

src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/controller/ReferralController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/model/SentenceInformation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/client/nDeliusIntegrationApi/NDeliusIntegrationApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/client/nDeliusIntegrationApi/model/CodeDescription.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/client/nDeliusIntegrationApi/model/NDeliusPersonalDetails.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/client/nDeliusIntegrationApi/model/NDeliusSentenceResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/SentenceService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/ServiceUserService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/controller/ReferralControllerIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/factory/EntityFactoriesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/factory/NDeliusSentenceResponseFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/factory/SentenceInformationFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/integration/wiremock/stubs/NDeliusApiStubs.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/utils/Utils.kt, wiremock_mappings/nDeliusMock.json
This PR returns the sentence information for a referral. A referral can either be on a `licence condition` or `community order` and returns different fields to the ui for each. We have set these fields to null and they will be filtered out on the ui to display the correct information.
```json
{
"sentenceType": "ORA Community Order (6 Months)",
"releaseType": null,
"licenceConditions": [],
"licenceEndDate": null,
"postSentenceSupervisionStartDate": null,
"postSentenceSupervisionEndDate": null,
"twoThirdsPoint": null,
"orderRequirements": [
{
"code": "RARREQ",
"description": "Rehabilitation Activity Requirement (RAR)"
},
{
"code": "724",
"description": "Building Skills for Recovery (BSR)"
},
{
"code": "CSPE06",
"description": "Curfew"
}
],
"orderEndDate": "23 March 2025",
"dateRetrieved": …
```
=> APG-941: Sentence Information endpoint

wiremock_mappings/nDeliusMock.json
- **What has been changed?**
Adjusted the URL path patterns to use regex anchors in WireMock to improve mock handling for offence details retrieval within the NDelius API integration.
`/case/.*/sentence/.*` was also mocking `/case/.*/sentence/.*/offences `
- **Why is this change necessary?**
The offence history URL was never being match due to the earlier sentence url definition
=> Refine URL patterns for offence details mocks in WireMock

wiremock_mappings/nDeliusMock.json
Added priorities to WireMock mappings for sentence and offence retrieval in NDelius, ensuring more predictable and accurate response handling during testing.
=> APG-1125 Add priorities to NDelius WireMock sentence and offence mocks

src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/model/risksAndNeeds/LearningNeeds.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/client/oasysApi/OasysApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/client/oasysApi/model/risksAndNeeds/OasysAccommodation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/RisksAndNeedsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/controller/RisksAndNeedsControllerIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/client/oasysApi/OasysApiClientIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/factory/oasys/OasysAccommodationFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/integration/wiremock/stubs/OasysApiStubs.kt
A few additional fields have been added to the LearningNeeds API model object that are needed in the UI.
This pull request therefore introduces functionality to retrieve accommodation details from OASys, including integration with the service layer and updated tests.
=> Add accommodation retrieval from OASys service

src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/config/JpaAuditConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/entity/DeliveryLocationPreferenceEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/repository/DeliveryLocationPreferenceRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/repository/OfficeRepository.kt, src/main/resources/db/migration/V19__create_delivery_location_preferences_tables.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/common/TestDataCleaner.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/common/TestDataGenerator.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/repository/DeliveryLocationPreferencesRepositoryIntegrationTest.kt
Added the following tables:
* delivery_location_preferences
* deliver_location_office_mapping
This allows a mapping between a referral and preferred office locations.
=> APG-1299: Create db tables and entities for deliveryLocationPreferences

src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/controller/DeliveryLocationPreferencesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/model/DeliveryLocationPreferencesFormData.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/DeliveryLocationPreferencesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/ReferralService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/controller/ReferralControllerIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/integration/wiremock/stubs/NDeliusApiStubs.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/repository/DeliveryLocationPreferencesRepositoryIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/DeliveryLocationPreferencesServiceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/ReferralServiceIntegrationTest.kt
This PR introduces a new API endpoint at `GET /bff/referral-delivery-location-preferences-form/{referral_id}`, which returns all of the data necessary to display the multi-page form to submit (or update) DeliveryLocationPreferences against a Referral.
It adds OpenAPI / Swagger docs detailing this endpoint.
We are using the BFF pattern because we need to fetch data from a variety of places (multiple nDelius endpoints, and our own database), and this moves the complexity of the multi-step fetch into the API allowing the UI to remain simple, 
The PR creates a new Service and Controller for the DeliveryLocationPreferences, using standard SpringBoot patterns.  There is nothing interesting or controversial here.
Using the refactored ReferralService (see below) to fetch both the manager and …
=> APG-1112: Create the DeliveryLocationPreference Form BFF endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/model/DeliveryLocationPreferencesFormData.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/DeliveryLocationPreferencesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/DeliveryLocationPreferencesServiceIntegrationTest.kt
**WHAT**
This commit adds the missing `.code` field (String) to the PDU being
returned for the DeliveryLocationPreferencesFormData
**WHY**
This code is necessary to save the PDU into the database when
creating/updating the DeliveryLocationPreferences in the Repository.
Without it, there would be un-necessary re-fetching of data and matching
based on `name` or `description` which feels unnecessarily complex and
risky.
=> fix(DeliveryLocationPreferences): Add the '.code' field to PDU

src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/ApiExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/controller/LdcController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/model/ldc/UpdateLdc.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/entity/ReferralLdcHistoryEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/LdcService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/controller/LdcControllerIntegrationTest.kt
* Adds a POST endpoint for Updating LDC status for a referral
* When a request to update ldc status comes through and `hasLdc` property in the body is not null then add entry into LDC history table and with LDC status True or False.
=> APG-1182: Add POST endpoint to update LDC status for a referral

src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/entity/ReferralEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/ReferralService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/client/findAndReferInterventionApi/FindAndReferInterventionApiClientIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/listener/DomainEventsListenerIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/DeliveryLocationPreferencesServiceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/ReferralServiceIntegrationTest.kt
Rename the  Licence condition value in the `ReferralEntitySourcedFrom` Enumeration.
When calling the FindAndRefer API, it is returning LICENCE_CONDITION not LICENSE_CONDITION.
The following error was found in the API dev logs:
`Exception occurred whilst processing request: Cannot deserialize value of type uk.gov.justice.digital.hmpps.accreditedprogrammesmanageanddeliverapi.entity.ReferralEntitySourcedFrom from String "LICENCE_CONDITION": not one of the values accepted for Enum class: [REQUIREMENT, LICENSE_CONDITION]`
=> [APG-1365] Rename `LICENSE_CONDITION` to `LICENCE_CONDITION` across the codebase

src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/controller/ReferralController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/model/ReferralStatusFormData.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/model/ReferralStatusHistory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/entity/ReferralStatusHistoryEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/ReferralService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/ReferralStatusService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/ReferralServiceIntegrationTest.kt
**WHAT**
This commit adds several fields (tag colour, user name, additional
comments) to the API endpoints that create and retrieve a list of
Referral Status Histories
**WHY**
In order to build the timeline UI, we need additional information about
the changes, so that we can provide our users with more information
=> APG-1314: Add fields to the ReferralStatusHistory get and create endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/controller/CaseListController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/repository/ReferralStatusDescriptionRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/repository/specification/GetReferralCaseListItemSpecification.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/ReferralCaseListItemService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/ReferralStatusService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/controller/CaseListControllerIntegrationTest.kt
On the UI we are able to select `Open` or `Closed` tabs. This PR adds the filtering for each of these tabs.
Depending on whether `OPEN` or `CLOSED` is passed through the controller. We retrieve a group of statuses depending on if they are `is_closed` in the ReferralStatusDescription table
=> APG-1378: Filter by open or closed cases

src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/controller/CaseListController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/model/caseList/CaseListFilterValues.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/repository/ReferralCaseListItemRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/service/ReferralCaseListItemService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/controller/CaseListControllerIntegrationTest.kt
In order for the ui to display the number of referrals in the other tab than it is currently in we need to provide a count for the `otherReferrals`. This means if the UI sends a request where it is in the `Open` tab we should count the `Closed` referrals and send this number back.
```json
{
"statusFilters": {
"open": [
"Awaiting allocation",
"Awaiting assessment",
"Breach (non-attendance)",
"Deferred",
"Deprioritised",
"On programme",
"Recall",
"Return to court",
"Scheduled",
"Suitable but not ready"
],
"closed": [
"Programme complete",
"Withdrawn"
]
},
"otherReferralsCount": 6
}
```
=> APG-1378: Adds the count of the opposite referrals tab to the bff filters

src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/model/caseList/ReferralCaseListItem.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/entity/ReferralCaseListItemViewEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/entity/ReferralEntity.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/accreditedprogrammesmanageanddeliverapi/api/controller/CaseListControllerIntegrationTest.kt
Adds the `reporting_team` and `pdu` to the response from the endpoint `/pdu/{openOrClosed}/-referrals`
An example of the JSON response is added below with the default example containing NULL values and the other value where there is a row present in the `referral_reporting_location` table.
```json
{
"content": [
{
"referralId": "39fde7e8-d2e3-472b-8364-5848bf673aa6",
"crn": "X718250",
"personName": "Edgar Schiller",
"referralStatus": "Awaiting assessment",
"cohort": "SEXUAL_OFFENCE",
"hasLdc": false,
"pdu": "PDU_1",
"reportingTeam": "TEAM_1"
},
{
"referralId": "6885d1f6-5958-40e0-9448-1ff8cc37e643",
"crn": "D002399",
"personName": "Karen Puckett",
"referralStatus": "Awaiting assessment",
"cohort": "GENERAL_OFFENCE",
"hasLdc": false,
"pdu": "UNKNOWN_PDU_NAME",
"reportingTeam": …
```
=> APG-1381: Add referral_reporting_location table and entities
